### ISSUE TITLE
[Feature request] New items category sort to top or bottom

### ISSUE THREAD

**Issue by xtoq** [p3lim-wow/Backpack#10]
Right now my "New Items" category shows up in the middle of the rest of the categories (see screenshot). Would be nice if it were at the bottom or at the top of the categories (I'm not picky which).

Loving this so far.

![image](https://cloud.githubusercontent.com/assets/120364/19421471/b4c49ec2-93c7-11e6-8566-3be4ec53efbf.png)

**Comment by p3lim** [comment]
See #2.

**Comment by xtoq** [comment]
Ah, okay, I read that ticket, but didn't realize it would cover this as well. (I took it as custom positioning for some reason.) Thanks!

**Comment by p3lim** [comment]
Custom positioning for all the containers basically.
