### ISSUE TITLE
Only see the junk category. Error message

### ISSUE THREAD

**Issue by bullsei** [p3lim-wow/Backpack#11]
- What version are you using?

70000.5-Beta

i only have the junk catetory. all other items are in the category new items.

```
4x Backpack\modules\Restack.lua:16: attempt to index local 'self' (a nil value)
Backpack\modules\Restack.lua:16: in function <Backpack\modules\Restack.lua:13>
Backpack\modules\Restack.lua:48: in function `init'
Backpack\core\Core.lua:64: in function <Backpack\core\Core.lua:50>
[C]: in function `securecall'
Backpack\core\EventHandler.lua:39: in function <Backpack\core\EventHandler.lua:35>

Locals:
self = nil
categoryIndex = 1002
isBank = true
Button = BackpackBankContainerMateriallagerRestack {
 0 = <userdata>
 Texture = BackpackBankContainerMateriallagerRestackTexture {
 }
 hideOfflineBank = true
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = BackpackBankContainerMateriallagerRestack {
 0 = <userdata>
 Texture = BackpackBankContainerMateriallagerRestackTexture {
 }
 hideOfflineBank = true
}
(*temporary) = "OnClick"
(*temporary) = <function> defined @Backpack\modules\Restack.lua:3
(*temporary) = nil
(*temporary) = BackpackBankContainerMateriallagerRestack {
 0 = <userdata>
 Texture = BackpackBankContainerMateriallagerRestackTexture {
 }
 hideOfflineBank = true
}
(*temporary) = "attempt to index local 'self' (a nil value)"
P = <table> {
 AddContainerSlot = <function> defined @Backpack\core\Containers.lua:31
 UpdateContainerCooldowns = <function> defined @Backpack\core\Slots.lua:177
 print = <function> defined @Backpack\core\Private.lua:7
 GetContainers = <function> defined @Backpack\core\Containers.lua:52
 UpdateContainerSlots = <function> defined @Backpack\core\Slots.lua:187
 RemoveCategorySlot = <function> defined @Backpack\core\Slots.lua:234
 Expose = <function> defined @Backpack\core\Core.lua:208
 GetSlot = <function> defined @Backpack\core\Slots.lua:64
 ResizeContainers = <function> defined @Backpack\core\Containers.lua:56
 CreateSlot = <function> defined @Backpack\core\Slots.lua:24
 RemoveContainerSlot = <function> defined @Backpack\core\Containers.lua:36
 CreateContainerButton = <function> defined @Backpack\core\ContainerButtons.lua:39
 name = "Backpack"
 noop = <function> defined @Backpack\core\Core.lua:302
 Fire = <function> defined @Backpack\core\Core.lua:181
 categorySlots = <table> {
 }
 UpdateSlotCooldown = <function> defined @Backpack\core\Slots.lua:170
 categories = <table> {
 }
 PositionContainers = <function> defined @Backpack\core\Containers.lua:103
 CreateContainer = <function> defined @Backpack\core\Containers.lua:4
 GetCategory = <function> defined @Backpack\core\Categories.lua:24
 query = <table> {
 }
 InitializeBank = <function> defined @Backpack\core\Core.lua:170
 SkinCallback = <function> defined @Backpack\core\Core.lua:198
 PositionSlots = <function> defined @Backpack\core\Slots.lua:247
 AddCategorySlot = <function> defined @Backpack\core\Slots.lua:217
 InitializeAllSlots = <function> defined @Backpack\core\Slots.lua:211
 UpdateAllSlots = <function> defined @Backpack\core\Slots.lua:193
 printf = <function> defined @Backpack\core\Private.lua:11
 GetAllContainers = <function> defined @Backpack\core\Containers.lua:48
 UpdateSlotInfo = <function> defined @Backpack\core\Slots.lua:139
 GetCategoryContainer = <function> defined @Backpack\core\Containers.lua:27
 UpdateSlot = <function> defined @Backpack\core\Slots.lua:80
 HasParent = <function> defined @Backpack\core\Slots.lua:76
 GetAllParents = <function> defined @Backpack\core\Slots.lua:72
 GetAllSlots = <function> defined @Backpack\core\Slots.lua:68
 modules = <table> {
 }
 Override = <function> defined @Backpack\core\Core.lua:191
 error = <function> defined @Backpack\core\Private.lua:16
 MixinAPI = <function> defined @Backpack\core\ContainerAPI.lua:121
}
OnClick = <function> defined @Backpack\modules\Restack.lua:3`
```

Using german locale (maybe thats the problem)

**Comment by bullsei** [comment]
i switched to english client for testing purpose. there everything seems to work fine. after that i switched back to german and the error occurred again(the categorys are still there)

**Comment by p3lim** [comment]
> i switched to english client for testing purpose. there everything seems to work fine. after that i switched back to german and the error occurred again(the categorys are still there). 

Very valuable information, thanks for that. I'll take a look at this during the weekend.

> i noticed another problem: the bag grows out of the screen (upwards) i know thats probably because i have too much stuff in my bags :) but it would be nice if it splitts into 2 columns to prevent to grow out of the screen

See issue #2.

**Comment by p3lim** [comment]
Your second issue should now be solved.

**Comment by bullsei** [comment]
Thanks for the reply. i downloaded all files from the repo and tested it out.
i made a screenshot. there is still a category cut off(barely visable i enabled framestack to show it):
https://1drv.ms/i/s!AjVne4_AjdPXiLsrSNCg1fVZCJ7UTQ

**Comment by p3lim** [comment]
The issue with other locales is separate.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Backpack/commit/d89fc4b20345cf1111f1173d821b29aa7a4bee7a

**Comment by p3lim** [comment]
When you _do_ test again, please try emptying the savedvariables if you get any errors:
```
/run BackpackDB = nil
/run BackpackPosition = nil
/reload
```

**Comment by bullsei** [comment]
it works now, all categorys are there. Thanks for that. Did you see the screenshot i linked above? It shows that the categorys are still growing out off the screen.

**Comment by p3lim** [comment]
> it works now, all categorys are there. Thanks for that. Did you see the screenshot i linked above? It shows that the categorys are still growing out off the screen.  

See the reply above:

> When you do test again, please try emptying the savedvariables if you get any errors:
> 
>     /run BackpackDB = nil
>     /run BackpackPosition = nil
>     /reload

**Comment by bullsei** [comment]
oh i see.  I deleted all saved variables tho before making that screenshot. Those 2 commands didn't change anything, there is still the BackpackContainerQuestItems growing out of the screen.

**Comment by p3lim** [comment]
What resolution are you using?

**Comment by bullsei** [comment]
1680 x 1050 (oldschoool, i know :) )

**Comment by p3lim** [comment]
> ui scale 0.9 (if that is relevant)

Very relevant, it's the causing factor, if you turned off custom ui scale right now it would work fine.
I'm gonna see if I can conjure some logic to handle that scaling though.

**Comment by bullsei** [comment]
i tried playing with auto scale before but everything is just way too small, especially the text. I appreciate your help.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Backpack/commit/f10b5b000c7a53a93d4aea1d823475d91e7bf9b4
https://github.com/p3lim-wow/Backpack/commit/303c964c4cb9bf8665d1853c3c1830d7f2f12ba5

Try now.

**Comment by bullsei** [comment]
That did it. Thanks 👍
