### ISSUE TITLE
Bank opens with backpack

### ISSUE THREAD

**Issue by Mishio595** [p3lim-wow/Backpack#12]
After visiting my bank, every time I open my bags my bank shows with it, even when not at a bank. I can't seem to find a way to close it.

**Comment by p3lim** [comment]
The keybindings the addon uses are the following:

- "Open all bags" - opens the bags **and** the bank
- "Open backpack" - opens just the bags

I plan on changing the behavior of the keybindings once I get the options GUI going, it's currently low-ish priority.

**Comment by Mishio595** [comment]
@p3lim Thanks!

**Comment by p3lim** [comment]
Leaving it open until a proper solution is introduced, and so other people can find it if they have the same issue.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Backpack/commit/97ab13e43691b30adf4eb71f5b1c105c4161dc56
