### ISSUE TITLE
Errors on login using latest version 70100.6-Beta

### ISSUE THREAD

**Issue by bullsei** [p3lim-wow/Backpack#15]
two errors occur (tested also with english and german client, deleted saved variabled before testing):

`20x Backpack_Classic\Backpack_Classic-70100.6-Beta.lua:85: Usage: GetItemQualityColor(index)
[C]: in function `GetItemQualityColor'
Backpack_Classic\Backpack_Classic-70100.6-Beta.lua:85: in function `?'
Backpack\core\Core.lua:216: in function `Override'
Backpack\core\Slots.lua:113: in function `UpdateSlot'
Backpack\core\Slots.lua:191: in function `UpdateContainerSlots'
Backpack\core\Core.lua:92: in function <Backpack\core\Core.lua:81>
[C]: in function `securecall'
Backpack\core\EventHandler.lua:39: in function <Backpack\core\EventHandler.lua:35>

Locals:
(*temporary) = nil`

second:

`
15x Backpack\core\Categories-Categories.lua:12: attempt to compare number with nil
Backpack\core\Categories-Categories.lua:12: in function <Backpack\core\Categories.lua:8>
[C]: in function `sort'
Backpack\core\Slots.lua:259: in function `PositionSlots'
Backpack\core\Core.lua:93: in function <Backpack\core\Core.lua:81>
[C]: in function `securecall'
Backpack\core\EventHandler.lua:39: in function <Backpack\core\EventHandler.lua:35>

Locals:
slotA = BackpackBag2Slot1 {
 timeSinceUpgradeCheck = 0
 BattlepayItemTexture = <unnamed> {
 }
 slotID = 1
 bagID = 2
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = BackpackBag2Slot1IconTexture {
 }
 categoryIndex = 1
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1122
 NewItem = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 Cooldown = BackpackBag2Slot1Cooldown {
 }
 SplitStack = <function> defined @FrameXML\ContainerFrame.lua:918
 itemCount = 1
 HighlightTexture = <unnamed> {
 }
 flash = <unnamed> {
 }
 category = <table> {
 }
 BattlePay = <unnamed> {
 }
 Icon = BackpackBag2Slot1IconTexture {
 }
 Container = Backpack {
 }
 JunkIcon = <unnamed> {
 }
 ItemLevel = BackpackBag2Slot1ItemLevel {
 }
 itemLevel = 0
 PushedTexture = <unnamed> {
 }
 itemID = 128363
 0 = <userdata>
 Flash = <unnamed> {
 }
 Count = BackpackBag2Slot1Count {
 }
 flashAnim = <unnamed> {
 }
 QuestIcon = BackpackBag2Slot1IconQuestTexture {
 }
 searchOverlay = BackpackBag2Slot1SearchOverlay {
 }
 NormalTexture = BackpackBag2Slot1NormalTexture {
 }
 parentContainer = Backpack {
 }
}
slotB = BackpackBag3Slot25 {
 timeSinceUpgradeCheck = 0
 BattlepayItemTexture = <unnamed> {
 }
 slotID = 25
 bagID = 3
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = BackpackBag3Slot25IconTexture {
 }
 categoryIndex = 1
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1122
 NewItem = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 Cooldown = BackpackBag3Slot25Cooldown {
 }
 SplitStack = <function> defined @FrameXML\ContainerFrame.lua:918
 itemCount = 1
 HighlightTexture = <unnamed> {
 }
 flash = <unnamed> {
 }
 category = <table> {
 }
 BattlePay = <unnamed> {
 }
 Icon = BackpackBag3Slot25IconTexture {
 }
 Container = Backpack {
 }
 JunkIcon = <unnamed> {
 }
 ItemLevel = BackpackBag3Slot25ItemLevel {
 }
 itemLevel = 60
 PushedTexture = <unnamed> {
 }
 itemID = 27944
 itemQuality = 1
 0 = <userdata>
 Flash = <unnamed> {
 }
 Count = BackpackBag3Slot25Count {
 }
 flashAnim = <unnamed> {
 }
 QuestIcon = BackpackBag3Slot25IconQuestTexture {
 }
 searchOverlay = BackpackBag3Slot25SearchOverlay {
 }
 NormalTexture = BackpackBag3Slot25NormalTexture {
 }
 parentContainer = Backpack {
 }
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to compare number with nil"
`

**Comment by bullsei** [comment]
holy shit, you are fast. Thanks 👍

**Comment by p3lim** [comment]
I assume that fixes it, it's probably a caching issue.

**Comment by bullsei** [comment]
still getting 2 erros. now i get 

`
8x Backpack_Classic\Backpack_Classic-70100.6-Beta.lua:100: Usage: GetItemInfoInstant(itemID|"name"|"itemlink")
[C]: in function `GetItemInfoInstant'
Backpack_Classic\Backpack_Classic-70100.6-Beta.lua:100: in function `?'
Backpack\core\Core.lua:216: in function `Override'
Backpack\core\Slots.lua:113: in function `UpdateSlot'
Backpack\core\Slots.lua:191: in function `UpdateContainerSlots'
Backpack\core\Core.lua:92: in function <Backpack\core\Core.lua:81>
[C]: in function `securecall'
Backpack\core\EventHandler.lua:39: in function <Backpack\core\EventHandler.lua:35>

Locals:
(*temporary) = nil
`

**Comment by p3lim** [comment]
Did you just copy-paste the changes in that commit?
Because lines don't match up.

**Comment by bullsei** [comment]
i opened the file and deleted red lines and copied the green lines into the file and delted the +characters

**Comment by bullsei** [comment]
i heard there is a new function for that with 7.1 GetDetailedItemLevelInfo
http://www.wowinterface.com/forums/showthread.php?t=54544

**Comment by p3lim** [comment]
GetItemInfo is accurate enough for upgrades when passing links instead of IDs, but possibly not downgrades (which I don't have a use for anyways).

**Comment by p3lim** [comment]
Did the last fix work btw?

**Comment by bullsei** [comment]
No chance to test right now. I had to go. Testing it when I am back home in a few hours.

**Comment by Mishio595** [comment]
I'm still getting and error causing only the main inventory to show up. 

41x
 Backpack\core\Containers.lua:113: attempt to index field 'containerOrder' (a nil value)
Backpack\core\Containers.lua:113: in function <Backpack\core\Containers.lua:108>
Backpack\core\Containers.lua:128: in function 'UpdateContainerPositions'
Backpack\core\Core.lua:77: in function <Backpack\core\Core.lua:76>
[C]:: in function 'securecall'
Backpack\core\EventHandler.lua:39: in function <Backpack\core\EventHandler.lua:35>

Locals:
parentContainer = Backpack {
 0 = <userdata>
 GetContainerNumFreeSlots = <function> defined @Backpack\core\ContainerAPI.lua:38
 slots = <table> {
 }
 GetContainerItemDurability = <function> defined @Backpack\core\ContainerAPI.lua:20
 GetContainerItemID = <function> defined @Backpack\core\ContainerAPI.lua:20
 extraPaddingY = 32
 Toggle = <function> defined @Backpack\core\Core.lua:238
 GetContainerItemInfo = <function> defined @Backpack\core\ContainerAPI.lua:20
 anchor = BackpackAnchor {
 }
 Title = BackpackTitle {
 }
 Override = <function> defined @Backpack\core\Core.lua:315
 numSlots = 0
 GetContainerItemCooldown = <function> defined @Backpack\core\ContainerAPI.lua:20
 name = "Inventory"
 type = 1
 On = <function> defined @Backpack\core\Core.lua:270
 AddModule = <function> defined @Backpack\core\Modules.lua:11
 EnableCategory = <function> defined @Backpack\core\Categories.lua:120
 AddLayout = <function> defined @Backpack\core\Core.lua:283
 GetContainerNumSlots = <function> defined @Backpack\core\ContainerAPI.lua:38
 AddCategory = <function> defined @Backpack\core\Categories.lua:47
 DisableCategory = <function> defined @Backpack\core\Categories.lua:97
 GetContainerItemEquipmentSetInfo = <function> defined @Backpack\core\ContainerAPI.lua:20
 GetContainerItemQuestInfo = <function> defined @Backpack\core\ContainerAPI.lua:20
 GetContainerItemLink = <function> defined @Backpack\core\ContainerAPI.lua:20
}
parentContainerType = 1
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = Backpack {
 }
 2 = BackpackContainerErronous {
 }
 1000 = BackpackContainerJunk {
 }
 50 = BackpackContainerProfessions {
 }
 70 = BackpackContainerWorldEvents {
 }
 41 = BackpackContainerConsumables {
 }
 30 = BackpackContainerEquipment {
 }
 31 = BackpackContainerEquipmentSets {
 }
 1001 = BackpackContainerNewItems {
 }
 10 = BackpackContainerArtifactPower {
 }
 20 = BackpackContainerQuestItems {
 }
 40 = BackpackContainerTradeGoods {
 }
 80 = BackpackContainerCollections {
 }
 60 = BackpackContainerTeleporters {
 }
}
(for control) = 2
categoryIndex = 2
Container = BackpackContainerErronous {
 0 = <userdata>
 name = "Erroneous"
 extraPaddingY = 16
 anchor = BackpackContainerErronousAnchor {
 }
 Title = BackpackContainerErronousTitle {
 }
 slots = <table> {
 }
 numSlots = 0
}
found = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'containerOrder' (a nil value)"
containers = <table> {
 (null) = <table> {
 }
 (null) = <table> {
 }
}

**Comment by bullsei** [comment]
still getting the following error (i downloaded the zip from the repo):
`8x Backpack_Classic\Backpack_Classic-@project-version@.lua:96: Usage: GetItemInfoInstant(itemID|"name"|"itemlink")
[C]: in function `GetItemInfoInstant'
Backpack_Classic\Backpack_Classic-@project-version@.lua:96: in function `?'
Backpack\core\Core.lua:216: in function `Override'
Backpack\core\Slots.lua:113: in function `UpdateSlot'
Backpack\core\Slots.lua:191: in function `UpdateContainerSlots'
Backpack\core\Core.lua:92: in function <Backpack\core\Core.lua:81>
[C]: in function `securecall'
Backpack\core\EventHandler.lua:39: in function <Backpack\core\EventHandler.lua:35>

Locals:
(*temporary) = nil`

**Comment by p3lim** [comment]
@Mishio595 
`/run BackpackDB = nil` then reload/relog.

**Comment by Mishio595** [comment]
@p3lim 
OMG Thank you so much!

**Comment by p3lim** [comment]
@bullsei https://github.com/p3lim-wow/Backpack/commit/101798a366e1d76c764bcfdeaaa0a3f1f9deacbb
@Mishio595 https://github.com/p3lim-wow/Backpack/commit/9d8b6a4717031495730ca4f9153dff37d531f619

**Comment by bullsei** [comment]
pressing on the button to reset the new category i get the following error:

`
1x Backpack_Classic\Backpack_Classic-@project-version@.lua:142: BackpackContainerArtifactPowerTitle:SetFormattedText(): Font not set
[C]: in function `SetFormattedText'
Backpack_Classic\Backpack_Classic-@project-version@.lua:142: in function <Backpack_Classic\Backpack_Classic.lua:117>
[C]: in function `Show'
Backpack\core\Core.lua:263: in function `Toggle'
Backpack\core\Blizzard.lua:4: in function `ToggleBackpack'
FrameXML\MainMenuBarBagButtons.lua:54: in function `BackpackButton_OnClick'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = BackpackContainerArtifactPowerTitle {
 0 = <userdata>
}
(*temporary) = "%s |cff00ff00(%s)|r"
(*temporary) = "Artefaktmacht"
(*temporary) = "1.210"

`

**Comment by bullsei** [comment]
couldn't reproduce this error since, maybe still an old version was loaded.
