### ISSUE TITLE
feature request: show BOE and BOA on the item slot.

### ISSUE THREAD

**Issue by solor** [p3lim-wow/Backpack#27]
like this one http://www.wowinterface.com/downloads/info23465-BindsWhen.html
hope this feature could be introduced in.

**Comment by p3lim** [comment]
Could just to ask @Phanx if she could add this to her addon:

```Lua
tinsert(addons, function()
	if(not Backpack) then
		return true
	end

	Backpack:On('PostUpdateSlot', function(Button)
		local count = Button.itemCount
		local text = (not count or count < 2) and GetBindText(Button.bagID, Button.slotID)
		SetItemButtonBindType(Button, text)
	end)
end)
```

**Comment by p3lim** [comment]
Added support in the latest version of BindsWhen: https://github.com/phanx-wow/BindsWhen/commit/d77a5308257527c2e81936af94a0e0a2b56e7087
