### ISSUE TITLE
RUru locale

### ISSUE THREAD

**Issue by Devimax** [p3lim-wow/Backpack#28]
Version 7001.10 betta!
I did not work the Russian language!
I did the [translation](https://drive.google.com/open?id=0B8VPSRLPHU75cmZMV0VIdlRLX1E), but the font does not support the Russian! temporarily replaced the font to [Homespun](https://drive.google.com/open?id=0B8VPSRLPHU75MzFxTEpjeTdSNU0), only had to change all font sizes to 10.

Версия 7001.10 бетта!
Не работал русский язык!
Я сделал перевод, но шрифт не поддерживает русский! временно заменил шрифт на  Homespun

, только пришлось все размеры шрифта изменить на 10.

перевод - locale https://drive.google.com/open?id=0B8VPSRLPHU75cmZMV0VIdlRLX1E
шрифт - font https://drive.google.com/open?id=0B8VPSRLPHU75MzFxTEpjeTdSNU0
![wowscrnshot_120216_231600](https://cloud.githubusercontent.com/assets/24323352/20848960/717da7ce-b8e5-11e6-8a92-461bf010c9a2.jpg)

**Comment by p3lim** [comment]
Please attach the code directly here.

**Comment by Devimax** [comment]
yes ELVui

**Comment by p3lim** [comment]
Related to #29
