### ISSUE TITLE
Update artifact power total count when bag is opened

### ISSUE THREAD

**Issue by bullsei** [p3lim-wow/Backpack#30]
Hi,

it would be nice if the total count would also update when the bags are opened. for example you go to your mailbox and your bags automatically open, collect your artifact power items and the items get assigned to the artifact power category but the total ap count doesn't update. don't know if this problem only exists for artifact power or for other stuff too.

**Comment by p3lim** [comment]
That count is specific for the artifact power in your bags, and I'm aware it doesn't update except on show (was designed that way).

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Backpack/commit/0d3e5d67cc0956448e9e2df925539413a849cc27
