### ISSUE TITLE
Error when trying to open bags

### ISSUE THREAD

**Issue by bullsei** [p3lim-wow/Backpack#31]
- What version are you using? latest alpha from curse 70100.10-Beta-17-g5ff9b4a

- Can the issue be reproduced, and if so, how?
can't tell excactly, maybe has something todo with combat, it doesn't happen after logging fresh into the game, the error happened after updating today to the latest alpha (70100.10-Beta-17-g5ff9b4a)
- If there was an error message, please include it.

`35x Backpack\core\Core.lua:231: attempt to call field '?' (a number value)
Backpack\core\Core.lua:231: in function `Toggle'
Backpack\core\Blizzard.lua:12: in function <Backpack\core\Blizzard.lua:11>
[C]: in function `securecall'
FrameXML\UIParent.lua:2174: in function `ShowUIPanel'
FrameXML\UIParent.lua:2086: in function <FrameXML\UIParent.lua:2082>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:2868: in function `ShowUIPanel'
FrameXML\UIParent.lua:3715: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
self = Backpack {
 0 = <userdata>
 GetContainerNumFreeSlots = <function> defined @Backpack\core\ContainerAPI.lua:38
 slots = <table> {
 }
 GetContainerItemDurability = <function> defined @Backpack\core\ContainerAPI.lua:20
 GetContainerItemID = <function> defined @Backpack\core\ContainerAPI.lua:20
 extraPaddingY = 36
 anchor = BackpackAnchor {
 }
 GetContainerItemInfo = <function> defined @Backpack\core\ContainerAPI.lua:20
 Override = <function> defined @Backpack\core\Core.lua:308
 Currencies = <table> {
 }
 On = <function> defined @Backpack\core\Core.lua:263
 AddLayout = <function> defined @Backpack\core\Core.lua:276
 GetContainerNumSlots = <function> defined @Backpack\core\ContainerAPI.lua:38
 numSlots = 55
 Restack = BackpackRestack {
 }
 SearchBox = BackpackSearch {
 }
 Toggle = <function> defined @Backpack\core\Core.lua:226
 GetContainerItemLink = <function> defined @Backpack\core\ContainerAPI.lua:20
 GetContainerItemEquipmentSetInfo = <function> defined @Backpack\core\ContainerAPI.lua:20
 ResetNew = BackpackContainerNewItemsResetNew {
 }
 ToggleSellJunk = BackpackContainerJunkToggleSellJunk {
 }
 type = 1
 Money = BackpackMoney {
 }
 GetContainerItemCooldown = <function> defined @Backpack\core\ContainerAPI.lua:20
 EmptySlot = BackpackBag0Slot99 {
 }
 BagSlots = BackpackBagSlots {
 }
 DepositReagents = BackpackBankContainerReagentBankDepositReagents {
 }
 ToggleLock = BackpackToggleLock {
 }
 locked = true
 buttons = <table> {
 }
 Title = BackpackTitle {
 }
 AddCategory = <function> defined @Backpack\core\Categories.lua:47
 name = "Inventar"
 ToggleBagSlots = BackpackToggleBagSlots {
 }
 GetContainerItemQuestInfo = <function> defined @Backpack\core\ContainerAPI.lua:20
 AddModule = <function> defined @Backpack\core\Modules.lua:11
}
force = false
shouldShow = nil
shouldShowBank = nil
includeBank = nil
(*temporary) = 76
(*temporary) = "attempt to call field '?' (a number value)"
Bank = BackpackBank {
 0 = <userdata>
 type = 2
 buttons = <table> {
 }
 ResetNew = BackpackBankContainerNewItemsResetNew {
 }
 slots = <table> {
 }
 BagSlots = BackpackBankBagSlots {
 }
 ToggleLock = BackpackBankToggleLock {
 }
 name = "Inventar"
 Title = BackpackBankTitle {
 }
 extraPaddingY = 16
 anchor = BackpackBankAnchor {
 }
 ToggleBagSlots = BackpackBankToggleBagSlots {
 }
 numSlots = 0
 Restack = BackpackBankRestack {
 }
}
Backpack = Backpack {
 0 = <userdata>
 GetContainerNumFreeSlots = <function> defined @Backpack\core\ContainerAPI.lua:38
 slots = <table> {
 }
 GetContainerItemDurability = <function> defined @Backpack\core\ContainerAPI.lua:20
 GetContainerItemID = <function> defined @Backpack\core\ContainerAPI.lua:20
 extraPaddingY = 36
 anchor = BackpackAnchor {
 }
 GetContainerItemInfo = <function> defined @Backpack\core\ContainerAPI.lua:20
 Override = <function> defined @Backpack\core\Core.lua:308
 Currencies = <table> {
 }
 On = <function> defined @Backpack\core\Core.lua:263
 AddLayout = <function> defined @Backpack\core\Core.lua:276
 GetContainerNumSlots = <function> defined @Backpack\core\ContainerAPI.lua:38
 numSlots = 55
 Restack = BackpackRestack {
 }
 SearchBox = BackpackSearch {
 }
 Toggle = <function> defined @Backpack\core\Core.lua:226
 GetContainerItemLink = <function> defined @Backpack\core\ContainerAPI.lua:20
 GetContainerItemEquipmentSetInfo = <function> defined @Backpack\core\ContainerAPI.lua:20
 ResetNew = BackpackContainerNewItemsResetNew {
 }
 ToggleSellJunk = BackpackContainerJunkToggleSellJunk {
 }
 type = 1
 Money = BackpackMoney {
 }
 GetContainerItemCooldown = <function> defined @Backpack\core\ContainerAPI.lua:20
 EmptySlot = BackpackBag0Slot99 {
 }
 BagSlot`

**Comment by p3lim** [comment]
I wouldn't use the alpha versions put on curse, especially when I'm in the middle of working on something, there will be instabilities between commits.
That issue you just hit I'm pretty sure I've already fixed.

**Comment by bullsei** [comment]
i see, my bad :)

**Comment by p3lim** [comment]
You didn't do anything wrong, I'm just giving you advice, those versions are pretty much guaranteed to not work.

**Comment by bullsei** [comment]
Using that alpha setting for all my addons, I should keep in mind that they are called alpha for a reason :)
Feel free to close
