### ISSUE TITLE
Manually specifying container columns split

### ISSUE THREAD

**Issue by solor** [p3lim-wow/Backpack#33]
a single row looks too height :confounded:

**Comment by p3lim** [comment]
Add `Container.columns = 3` or 4 or anything you want really after this line:
https://github.com/p3lim-wow/Backpack/blob/70100.10-Beta/layout_ext/Backpack_Classic.lua#L29

It's up to the layout to decide, but that's how you do it with the default layout.

**Comment by solor** [comment]
sorry about my poor English, I mean 3 or 4 container in 1 row, not how many slot in 1 column :rofl: 

![untitled](https://cloud.githubusercontent.com/assets/156806/21664757/8db29eec-d323-11e6-8fcb-37d1e2c096a6.jpg)

**Comment by p3lim** [comment]
Ah, that will auto-adjust based on your screen height, there is no current way to limit that.

**Comment by solor** [comment]
thanks for response, but 1 row is really inconvenient

**Comment by p3lim** [comment]
See #2.
