### ISSUE TITLE
slot size issue

### ISSUE THREAD

**Issue by solor** [p3lim-wow/Backpack#35]
```Slot:SetSize(38, 38)``` 
set slot size bigger than 34, buttons overlap each other and no spacing

![untitled2](https://cloud.githubusercontent.com/assets/156806/21666298/d015d9f4-d32b-11e6-8263-00d9150a632e.jpg)

**Comment by p3lim** [comment]
You need to define `Container.slotSize` or `Container.slotSizeX` and `Container.slotSizeY`. The default layout doesn't need to because the default value for all of those are 32.

**Comment by solor** [comment]
thanks
