### ISSUE TITLE
LibDropdown missing

### ISSUE THREAD

**Issue by markhaehnel** [p3lim-wow/Backpack#37]
Using the current version (99ba01158b82c618ab233c4966ad8dce2faaf567) throws some LUA errors about the missing LibDropdown.

**Comment by p3lim** [comment]
You really shouldn't use alpha versions of this addon, they are not going to work most of the time.

**Comment by EZTEQ** [comment]
Just was a reminder 😀

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Backpack/commit/97d166b6035a20d822e25b44a43403c4af5cc307
