### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by ewakramo** [p3lim-wow/Backpack#42]
please add an option for classic skin/layout (blizz default bag skins)

**Comment by p3lim** [comment]
The point of this project, mainly, is to create a framework to easily implement bag addons with different skins, like how [oUF](https://github.com/oUF-wow/oUF) does for unit frames.
The "Classic" skin is merely an example layout using this framework.

However, I've heard rumors that a certain someone (@ls-) wanted to make a Blizzard-themed layout using Backpack, so you could ask him if he plans to actually make it.

**Comment by ls-** [comment]
I may actually make one a bit later, I'm a bit busy atm though: rewriting one of my addons.

**Comment by ewakramo** [comment]
ok ty ill follow

**Comment by ls-** [comment]
Just letting you know that I started working on Blizz-like skin, after playing w/ Blizz textures for a while I've decided to use my own textures from my ls: UI for icon and bag borders.

Obv WIP and many things will be tweaked:
![Imgur](https://i.imgur.com/BALdot4.png)

I also need to draw and/or reuse Blizz textures for unlock, auto-sell, etc container buttons.

**Comment by p3lim** [comment]
Closing this as it's not relevant to the core nor the Classic layout, @ls- has basically taken over this issue.
