### ISSUE TITLE
Bug with 7.3.5

### ISSUE THREAD

**Issue by runamonk** [p3lim-wow/Backpack#60]
45x Backpack\core\Slots.lua:143: attempt to index local 'Slot' (a nil value)
Backpack\core\Slots.lua:143: in function `UpdateSlot'
Backpack\core\Slots.lua:239: in function `UpdateContainerSlots'
Backpack\core\Core.lua:82: in function <Backpack\core\Core.lua:71>
[C]: in function `securecall'
Backpack\core\EventHandler.lua:39: in function <Backpack\core\EventHandler.lua:35>

Locals:
bagID = 0
slotID = 17
event = "BAG_UPDATE"
itemID = 39211
itemLink = "|cff9d9d9d|Hitem:39211::::::::110:253::::::|h[Serrated Fang]|h|r"
category = <table> {
 index = 1000
 frameName = "Junk"
 sortFunc = <function> defined @Backpack\categories\Junk.lua:16
 filterFunc = <function> defined @Backpack\categories\Junk.lua:6
 name = "Junk"
}
categoryIndex = 1000
Slot = nil
(*temporary) = 0
(*temporary) = 17
(*temporary) = nil
(*temporary) = 13
(*temporary) = 1
(*temporary) = -1
(*temporary) = 13
(*temporary) = <table> {
 index = 1000
 frameName = "Junk"
 sortFunc = <function> defined @Backpack\categories\Junk.lua:16
 filterFunc = <function> defined @Backpack\categories\Junk.lua:6
 name = "Junk"
}
(*temporary) = true
(*temporary) = "attempt to index local 'Slot' (a nil value)"
P = <table> {
 AddContainerSlot = <function> defined @Backpack\core\Containers.lua:33
 UpdateContainerCooldowns = <function> defined @Backpack\core\Slots.lua:227
 print = <function> defined @Backpack\core\Private.lua:7
 GetContainers = <function> defined @Backpack\core\Containers.lua:54
 UpdateContainerSlots = <function> defined @Backpack\core\Slots.lua:237
 RemoveCategorySlot = <function> defined @Backpack\core\Slots.lua:293
 Expose = <function> defined @Backpack\core\Core.lua:222
 GetSlot = <function> defined @Backpack\core\Slots.lua:114
 Override = <function> defined @Backpack\core\Core.lua:205
 CreateSlot = <function> defined @Backpack\core\Slots.lua:71
 UpdateContainerSizes = <function> defined @Backpack\core\Containers.lua:62
 RemoveContainerSlot = <function> defined @Backpack\core\Containers.lua:38
 UpdateContainerPositions = <function> defined @Backpack\core\Containers.lua:134
 name = "Backpack"
 noop = <function> defined @Backpack\core\Core.lua:336
 Fire = <function> defined @Backpack\core\Core.lua:195
 categorySlots = <table> {
 }
 UpdateSlotCooldown = <function> defined @Backpack\core\Slots.lua:220
 categories = <table> {
 }
 CreateContainer = <function> defined @Backpack\core\Containers.lua:4
 HasContainer = <function> defined @Backpack\core\Containers.lua:58
 InitializePosition = <function> defined @Backpack\core\Position.lua:52
 query = <table> {
 }
 PositionSlots = <function> defined @Backpack\core\Slots.lua:306
 AddCategorySlot = <function> defined @Backpack\core\Slots.lua:276
 InitializeBank = <function> defined @Backpack\core\Core.lua:184
 SkinCallback = <function> defined @Backpack\core\Core.lua:212
 InitializeAllSlots = <function> defined @Backpack\core\Slots.lua:261
 UpdateAllSlots = <function> defined @Backpack\core\Slots.lua:243
 UpdateSlotInfo = <function> defined @Backpack\core\Slots.lua:189
 UpdateSlot = <function> defined @Backpack\core\Slots.lua:130
 printf = <function> defined @Backpack\core\Private.lua:11
 GetAllContainers = <function> defined @Backpack\core\Containers.lua:50
 HasParent = <function> defined @Backpack\core\Slots.lua:126
 GetCategoryContainer = <function> defined @Backpack\core\Containers.lua:29
 CreateContainerButton = <function> defined @Backpack\core\ContainerButtons.lua:39
 GetAllSlots = <function> defined @Backpack\core\Slots.lua:118
 GetAllParents = <function> defined @Backpack\core\Slots.lua:122
 AddCategory = <function> defined @Backpack\core\Categories.lua:45
 GetCategory = <function> defined @Backpack\core\Categories.lua:28
 LoadModules = <function> defined @Backpack\core\Modules.lua:21
 error = <function> defined @In

**Comment by runamonk** [comment]
btw this seems to be related to the four new slots that given to people with authenticators on their account.

I updated slots.lua > P.UpdateSlot() in order to do a little testing.

function P.UpdateSlot(bagID, slotID, event)
	if(Backpack:GetContainerItemInfo(bagID, slotID)) then
		local itemID = Backpack:GetContainerItemID(bagID, slotID)
		local itemLink = Backpack:GetContainerItemLink(bagID, slotID)

		local category = P.GetCategory(bagID, slotID, itemID)
		local categoryIndex = category.index

		local Slot = P.GetSlot(bagID, slotID)
		
----added for testing, all are bagid of 0 but slots are now 17, 18, 19, 20
		if Slot == nil then 
			print(bagID.." "..slotID);
			return 
		end

.....(snipped)...

**Comment by Luneli** [comment]
My friend found a fix for it, at least temporarily? 

function P.InitializeAllSlots(bagID)
	local numSlots = 16

... Change the 16 to a 20, and it works with the new 4 slots.
