### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by p3lim** [p3lim-wow/Backpack#8]
Need some proper icons for the default theme

- [x] Mark new items as known (arrow going in a loop? like the [temporary one](https://raw.githubusercontent.com/Gethe/wow-ui-textures/live/Buttons/UI-RefreshButton.PNG) (![](https://raw.githubusercontent.com/Gethe/wow-ui-textures/live/Buttons/UI-RefreshButton.PNG))
- [x] Toggle auto-vendor junk (trashcan)
- [x] Restack (clean) bags (boxes on top of boxes)
- [x] Deposit all reagents (arrow into a square perhaps?)
- [x] Toggle auto-deposit all reagents (not sure about this one, perhaps some derivation from the one above)
- [x] Toggle bag slots (also not sure, maybe just a bag)

The [search icon](https://raw.githubusercontent.com/Gethe/wow-ui-textures/live/COMMON/UI-Searchbox-Icon.PNG) (![](https://raw.githubusercontent.com/Gethe/wow-ui-textures/live/COMMON/UI-Searchbox-Icon.PNG)) for the search bar is provided by blizzard and is just fine.

**Comment by xtoq** [comment]
Designer here. What kind of help are you needing on this?

**Comment by p3lim** [comment]
Was thinking something very simple that represents the mentioned actions well.
The icons themselves should be 16x16 in size, and they need to be white on transparent background.
No gradient or anything.

I like the current icon for marking items as known (from the New category), so something along that vein.

I updated the list above with what the icon could/should represent (graphically).

**Comment by xtoq** [comment]
Okay, I use a great set of CC 3.0 (attribution) icons a lot, so I took a look at the entire set and I think I have some ideas. Here's a quick mockup below of the different icons and states.

![backpack-icons](https://cloud.githubusercontent.com/assets/120364/19524589/d48fd7f8-95e3-11e6-9f38-5baf61b41b93.png)

**New**: I like the checkmark, but the brain is interesting and memorable, and I couldn't resist including it.

**Toggled**: I think using a color overlay for the toggle state is probably simpler and less overhead than using a new icon, but if you'd like I can also put a green checkmark on the icons in the toggle state. Might be a little busy with the other arrows on the reagent icons. Let me know if you'd like to see that.

**Reagents**: I like the piggy bank personally but the box is probably more universally clear.

**Comment by p3lim** [comment]
I was thinking more pixelated styles, like this: ![](http://findicons.com/files/icons/2139/uidesign/16/delete.png) (random google search), and also single-color so that I can color and/or desaturate them from the addon instead.

Good suggestions though, the theme for the icons are great!

**Comment by xtoq** [comment]
So same visual idea, but line art. Gotcha, gimme until tomorrow, have some things going on today.

**Comment by p3lim** [comment]
No rush :)

**Comment by xtoq** [comment]
Okay! How about these? More what you're wanting?

![backpack-icons](https://cloud.githubusercontent.com/assets/120364/19818879/72fe2694-9d17-11e6-8165-33205b473ae8.png)

**Comment by p3lim** [comment]
Very nice!

I think I prefer the first restack icon (due to how it technically works for Backpack compared to how it works for the default bags).

> I can also do the outline versions. Just let me know!

What do you mean by outline versions?

**Comment by xtoq** [comment]
What I mean by outline versions are like this:

![backpack-icons](https://cloud.githubusercontent.com/assets/120364/19826038/9abe64a2-9d47-11e6-8513-9a29ff519d58.png)

I'm not a fan of most of these in outline form because of the delicate lines and too much whitespace for where they would be used, but I figured comparing them couldn't hurt.

Do you mean you prefer this icon ![image](https://cloud.githubusercontent.com/assets/120364/19826043/cec6e5e4-9d47-11e6-8ad0-88fccc4354bc.png) for restack?

**Comment by p3lim** [comment]
Do you mean you prefer this icon ![image](https://cloud.githubusercontent.com/assets/120364/19826043/cec6e5e4-9d47-11e6-8ad0-88fccc4354bc.png) for restack?

Yup, and I think I prefer the outline versions more as well 👍

**Comment by xtoq** [comment]
Sound great! Do you want the white areas transparent or filled with white?

What file format do you need these in?

**Comment by p3lim** [comment]
White areas transparent and png.

**Comment by xtoq** [comment]
Derp. Somehow I missed that in comment 3ish. Reading comprehension FTW!

Which deposit reagents icon do you prefer: ![image](https://cloud.githubusercontent.com/assets/120364/19826244/66a76642-9d4b-11e6-9103-0e6f2c6a3605.png) or ![image](https://cloud.githubusercontent.com/assets/120364/19826246/6fde30ec-9d4b-11e6-8d9f-3db7af220e87.png)?

**Comment by p3lim** [comment]
Not sure, they're both pretty great.

**Comment by xtoq** [comment]
Then you shall have both. Files attached!

[backpack-icons-1.0.0.zip](https://github.com/p3lim-wow/Backpack/files/559673/backpack-icons-1.0.0.zip)

**Comment by p3lim** [comment]
Tried them out, they look good, but they are really big compared to the other elements of the container.
Messed around with them, seems like 9x9 is the best size to go for.

**Comment by p3lim** [comment]
Thanks for all your help @xtoq, you kind of set the style for it, I ended up just drawing the final ones myself (although unsure about the bagslots one), 9x9 pixels wasn't that hard.

**Comment by xtoq** [comment]
Oh! Just woke up (weekend here), but I did work on some last night. Here's the ones I did as well, albeit almost exactly like you - 9x9 isn't a big canvas as you said. =) Although my sort icon looks wonky...

[backpack-icons-1.1.0.zip](https://github.com/p3lim-wow/Backpack/files/559942/backpack-icons-1.1.0.zip)

Anyways, so glad to help!

**Comment by p3lim** [comment]
Pig looks like an amputated chicken :p
Bag is nice though, might use that one.

**Comment by xtoq** [comment]
Yeah, putting that down to 9x9 was a struggle! Glad you like the bag though. If you need more design-y things, just yell!
