### ISSUE TITLE
Nomi Error

### ISSUE THREAD

**Issue by Thunder-Child** [p3lim-wow/Backpack#9]
- What version are you using?
70000.3-Beta

Date: 2016-10-14 15:48:23
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Backpack\core\Slots.lua line 93:
   attempt to index local 'Slot' (a nil value)
Debug:
   Backpack\core\Slots.lua:93: UpdateSlot()
   Backpack\core\Slots.lua:189: UpdateContainerSlots()
   Backpack\core\Slots.lua:206: UpdateAllSlots()
   Backpack\core\Core.lua:229: Toggle()
   Backpack\core\Blizzard.lua:8: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
bagID = -3
slotID = 18
event = "OnShow"
itemID = 124120
cached = "Leyblood"
_ = "[Leyblood]"
_ = 1
itemLevel = 101
category = <table> {
 name = "Reagent Bank"
 sortFunc = <function> defined @Interface\AddOns\Backpack\core\Categories.lua:8
 index = 1002
 filterFunc = <function> defined @Interface\AddOns\Backpack\categories\ReagentBank.lua:6
}
categoryIndex = 1002
Slot = nil
(*temporary) = -3
(*temporary) = 18
(*temporary) = nil
(*temporary) = 15
(*temporary) = 1
(*temporary) = -1
(*temporary) = 15
(*temporary) = <table> {
 name = "Reagent Bank"
 sortFunc = <function> defined @Interface\AddOns\Backpack\core\Categories.lua:8
 index = 1002
 filterFunc = <function> defined @Interface\AddOns\Backpack\categories\ReagentBank.lua:6
}
(*temporary) = true
(*temporary) = -3
(*temporary) = "attempt to index local 'Slot' (a nil value)"
P = <table> {
 AddContainerSlot = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:31
 UpdateContainerCooldowns = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:177
 print = <function> defined @Interface\AddOns\Backpack\core\Private.lua:7
 GetContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:52
 UpdateContainerSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:187
 RemoveCategorySlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:234
 Expose = <function> defined @Interface\AddOns\Backpack\core\Core.lua:208
 GetSlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:64
 ResizeContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:56
 CreateSlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:24
 RemoveContainerSlot = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:36
 CreateContainerButton = <function> defined @Interface\AddOns\Backpack\core\ContainerButtons.lua:39
 name = "Backpack"
 noop = <function> defined @Interface\AddOns\Backpack\core\Core.lua:302
 Fire = <function> defined @Interface\AddOns\Backpack\core\Core.lua:181
 categorySlots = <table> {
 }
 UpdateSlotCooldown = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:170
 categories = <table> {
 }
 PositionContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:103
 CreateContainer = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:4
 GetCategory = <function> defined @Interface\AddOns\Backpack\core\Categories.lua:24
 query = <table> {
 }
 InitializeBank = <function> defined @Interface\AddOns\Backpack\core\Core.lua:170
 SkinCallback = <function> defined @Interface\AddOns\Backpack\core\Core.lua:198
 PositionSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:247
 AddCategorySlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:217
 InitializeAllSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:211
 UpdateAllSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:193
 printf = <function> defined @Interface\AddOns\Backpack\core\Private.lua:11
 GetAllContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:48
 UpdateSlotInfo = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:139
 GetCategoryContainer = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:27
 UpdateSlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:80
 HasParent = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:76
 GetAllParents = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:72
 GetAllSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:68
 modules = <table> {
 }
 Override = <function> defined @Interface\AddOns\Backpack\core\Core.lua:191
 error = <function> defined @Interface\AddOns\Backpack\core\Private.lua:16
 MixinAPI = <function> defined @Interface\AddOns\Backpack\core\ContainerAPI.lua:121
}

AddOns:
  KalielsTracker, v2.0.6
  Swatter, v7.1.5675 (TasmanianThylacine)
  WowheadLooter, v60014
  Ace3, v
  AceGUI30SharedMediaWidgets, v
  AckisRecipeList, v7.0.3.8
  AckisRecipeListQuickScan, v7.0.3.3
  ACP, v3.4.29 
  AdvancedInterfaceOptions, v1.0.5
  Altoholic, vr171
  AngryWorldQuests, v
  Archy, v7.0.3.17
  Babylonian, v5.1.DEV.332(/embedded)
  Backpack, v70000.3-Beta
  BackpackClassic, v70000.3-Beta
  Bartender4, v4.7.2
  BigWigs, vv18
  BrokerCurrency, v7.0.3.2
  BrokerDurabilityInfo, v1.24
  BrokerEverything, v2.17-Release
  BrokerGarrison, v2.0.8.1
  BrokerMoneyFu, v70000-1
  BrokerProfessionsMenu, v7.0.3.15
  BrokeruClock, vv3.3.9
  ChocolateBar, vv3.0.2
  Configator, v5.1.DEV.406(/embedded)
  CooldownCount, v7.0.1
  CrapAway, v
  Crosshairs, v0.3
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr54
  DBMCore, v
  DBMDefaultSkin, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DejaCharacterStats, v7.0.3 r16
  ElkBuffBars, v2.5.0-188
  Fizzle, v70000-1
  GatherMate2, v1.37.1
  IceHUD, v1.10.9
  Informant, v7.1.5675 (TasmanianThylacine)
  KuiNameplates, v
  KuiNameplatesCore, v
  KuiNameplatesCoreConfig, v
  LibExtraTip, v5.12.DEV.412(/embedded)
  LibSharedMedia30, v3.0-95
  lsToasts, v1.12
  Mapster, v1.7.2
  Masque, v7.0.1
  MasqueApathy, v7.0.0
  MasqueCaith, v7.0.0
  MasqueEntropy, v7.0.0
  MasqueLiteStep, v7.0.0
  MasqueOnyx, v7.0.0
  MasqueRenaitre, vv7.0.3
  MasqueSerenity, v7.0.0
  MikScrollingBattleText, v5.7.146
  MoveAnything, v16.1.0
  NomiCakes, v7.0.3.13
  OmniCC, v7.0.1
  Pawn, v2.1
  PerfectRaid, vv70000-1.0.0
  PetTracker, v7.0.2
  PetTrackerBreeds, v
  PetTrackerConfig, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  PitBull4, vv4.0.9
  PitBull4Aggro, vv4.0.9
  PitBull4AltManaBar, vv4.0.9
  PitBull4AltPowerBar, vv4.0.9
  PitBull4ArtifactPowerBar, vv4.0.9
  PitBull4Aura, vv4.0.9
  PitBull4Background, vv4.0.9
  PitBull4BattlePet, vv4.0.9
  PitBull4BlankSpace, vv4.0.9
  PitBull4Border, vv4.0.9
  PitBull4CastBar, vv4.0.9
  PitBull4CastBarLatency, vv4.0.9
  PitBull4CombatFader, vv4.0.9
  PitBull4CombatIcon, vv4.0.9
  PitBull4CombatText, vv4.0.9
  PitBull4ComboPoints, vv4.0.9
  PitBull4ExperienceBar, vv4.0.9
  PitBull4HealthBar, vv4.0.9
  PitBull4HideBlizzard, vv4.0.9
  PitBull4Highlight, vv4.0.9
  PitBull4HostilityFader, vv4.0.9
  PitBull4LeaderIcon, vv4.0.9
  PitBull4LuaTexts, vv4.0.9
  PitBull4MasterLooterIcon, vv4.0.9
  PitBull4PhaseIcon, vv4.0.9
  PitBull4Portrait, vv4.0.9
  PitBull4PowerBar, vv4.0.9
  PitBull4PvPIcon, vv4.0.9
  PitBull4QuestIcon, vv4.0.9
  PitBull4RaidTargetIcon, vv4.0.9
  PitBull4RangeFader, vv4.0.9
  PitBull4ReadyCheckIcon, vv4.0.9
  PitBull4ReputationBar, vv4.0.9
  PitBull4RestIcon, vv4.0.9
  PitBull4RoleIcon, vv4.0.9
  PitBull4Sounds, vv4.0.9
  PitBull4ThreatBar, vv4.0.9
  PitBull4Totems, vv4.0.9
  PitBull4VisualHeal, vv4.0.9
  PitBull4VoiceIcon, vv4.0.9
  Postal, vv3.5.8
  Prat30, v3.6.15      
  Prat30Libraries, v
  Quartz, v3.3.1
  Recount, vv7.0.3k release
  RelicInspector, v1.11
  SexyMap, vv7.0.0
  SharedMedia, v3.0.7-188
  Stubby, v7.1.5675 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  TipTac, v16.08.30
  TipTacItemRef, v16.08.30
  TipTacTalents, v16.07.21
  WorldFlightMap, vr5
  WoWDBProfiler, v
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=e6f)

**Comment by Thunder-Child** [comment]
Found another error in swatter.  Must have been the first one.

Date: 2016-10-14 15:46:19
ID: -1
Error occured in: Global
Count: 43
Message: ..\AddOns\Backpack\core\Slots.lua line 93:
   attempt to index local 'Slot' (a nil value)
Debug:
   Backpack\core\Slots.lua:93: UpdateSlot()
   Backpack\core\Core.lua:123:
      Backpack\core\Core.lua:122
   [C]: securecall()
   Backpack\core\EventHandler.lua:39:
      Backpack\core\EventHandler.lua:35
Locals:
bagID = -3
slotID = 18
event = "PLAYERREAGENTBANKSLOTS_CHANGED"
itemID = 124120
cached = "Leyblood"
_ = "[Leyblood]"
_ = 1
itemLevel = 101
category = <table> {
 name = "Reagent Bank"
 sortFunc = <function> defined @Interface\AddOns\Backpack\core\Categories.lua:8
 index = 1002
 filterFunc = <function> defined @Interface\AddOns\Backpack\categories\ReagentBank.lua:6
}
categoryIndex = 1002
Slot = nil
(*temporary) = -3
(*temporary) = 18
(*temporary) = nil
(*temporary) = 15
(*temporary) = 1
(*temporary) = -1
(*temporary) = 15
(*temporary) = <table> {
 name = "Reagent Bank"
 sortFunc = <function> defined @Interface\AddOns\Backpack\core\Categories.lua:8
 index = 1002
 filterFunc = <function> defined @Interface\AddOns\Backpack\categories\ReagentBank.lua:6
}
(*temporary) = true
(*temporary) = -3
(*temporary) = "attempt to index local 'Slot' (a nil value)"
P = <table> {
 AddContainerSlot = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:31
 UpdateContainerCooldowns = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:177
 print = <function> defined @Interface\AddOns\Backpack\core\Private.lua:7
 GetContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:52
 UpdateContainerSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:187
 RemoveCategorySlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:234
 Expose = <function> defined @Interface\AddOns\Backpack\core\Core.lua:208
 GetSlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:64
 ResizeContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:56
 CreateSlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:24
 RemoveContainerSlot = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:36
 CreateContainerButton = <function> defined @Interface\AddOns\Backpack\core\ContainerButtons.lua:39
 name = "Backpack"
 noop = <function> defined @Interface\AddOns\Backpack\core\Core.lua:302
 Fire = <function> defined @Interface\AddOns\Backpack\core\Core.lua:181
 categorySlots = <table> {
 }
 UpdateSlotCooldown = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:170
 categories = <table> {
 }
 PositionContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:103
 CreateContainer = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:4
 GetCategory = <function> defined @Interface\AddOns\Backpack\core\Categories.lua:24
 query = <table> {
 }
 InitializeBank = <function> defined @Interface\AddOns\Backpack\core\Core.lua:170
 SkinCallback = <function> defined @Interface\AddOns\Backpack\core\Core.lua:198
 PositionSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:247
 AddCategorySlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:217
 InitializeAllSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:211
 UpdateAllSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:193
 printf = <function> defined @Interface\AddOns\Backpack\core\Private.lua:11
 GetAllContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:48
 UpdateSlotInfo = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:139
 GetCategoryContainer = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:27
 UpdateSlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:80
 HasParent = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:76
 GetAllParents = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:72
 GetAllSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:68
 modules = <table> {
 }
 Override = <function> defined @Interface\AddOns\Backpack\core\Core.lua:191
 error = <function> defined @Interface\AddOns\Backpack\core\Private.lua:16
 MixinAPI = <function> defined @Interface\AddOns\Backpack\core\ContainerAPI.lua:121
}

AddOns:
  KalielsTracker, v2.0.6
  Swatter, v7.1.5675 (TasmanianThylacine)
  WowheadLooter, v60014
  Ace3, v
  AceGUI30SharedMediaWidgets, v
  AckisRecipeList, v7.0.3.8
  AckisRecipeListQuickScan, v7.0.3.3
  ACP, v3.4.29 
  AdvancedInterfaceOptions, v1.0.5
  Altoholic, vr171
  AngryWorldQuests, v
  Archy, v7.0.3.17
  Babylonian, v5.1.DEV.332(/embedded)
  Backpack, v70000.3-Beta
  BackpackClassic, v70000.3-Beta
  Bartender4, v4.7.2
  BigWigs, vv18
  BrokerCurrency, v7.0.3.2
  BrokerDurabilityInfo, v1.24
  BrokerEverything, v2.17-Release
  BrokerGarrison, v2.0.8.1
  BrokerMoneyFu, v70000-1
  BrokerProfessionsMenu, v7.0.3.15
  BrokeruClock, vv3.3.9
  ChocolateBar, vv3.0.2
  Configator, v5.1.DEV.406(/embedded)
  CooldownCount, v7.0.1
  CrapAway, v
  Crosshairs, v0.3
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr54
  DBMCore, v
  DBMDefaultSkin, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DejaCharacterStats, v7.0.3 r16
  ElkBuffBars, v2.5.0-188
  Fizzle, v70000-1
  GatherMate2, v1.37.1
  IceHUD, v1.10.9
  Informant, v7.1.5675 (TasmanianThylacine)
  KuiNameplates, v
  KuiNameplatesCore, v
  KuiNameplatesCoreConfig, v
  LibExtraTip, v5.12.DEV.412(/embedded)
  LibSharedMedia30, v3.0-95
  lsToasts, v1.12
  Mapster, v1.7.2
  Masque, v7.0.1
  MasqueApathy, v7.0.0
  MasqueCaith, v7.0.0
  MasqueEntropy, v7.0.0
  MasqueLiteStep, v7.0.0
  MasqueOnyx, v7.0.0
  MasqueRenaitre, vv7.0.3
  MasqueSerenity, v7.0.0
  MikScrollingBattleText, v5.7.146
  MoveAnything, v16.1.0
  NomiCakes, v7.0.3.13
  OmniCC, v7.0.1
  OmniCCConfig, v
  Pawn, v2.1
  PerfectRaid, vv70000-1.0.0
  PetTracker, v7.0.2
  PetTrackerBreeds, v
  PetTrackerConfig, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  PitBull4, vv4.0.9
  PitBull4Aggro, vv4.0.9
  PitBull4AltManaBar, vv4.0.9
  PitBull4AltPowerBar, vv4.0.9
  PitBull4ArtifactPowerBar, vv4.0.9
  PitBull4Aura, vv4.0.9
  PitBull4Background, vv4.0.9
  PitBull4BattlePet, vv4.0.9
  PitBull4BlankSpace, vv4.0.9
  PitBull4Border, vv4.0.9
  PitBull4CastBar, vv4.0.9
  PitBull4CastBarLatency, vv4.0.9
  PitBull4CombatFader, vv4.0.9
  PitBull4CombatIcon, vv4.0.9
  PitBull4CombatText, vv4.0.9
  PitBull4ComboPoints, vv4.0.9
  PitBull4ExperienceBar, vv4.0.9
  PitBull4HealthBar, vv4.0.9
  PitBull4HideBlizzard, vv4.0.9
  PitBull4Highlight, vv4.0.9
  PitBull4HostilityFader, vv4.0.9
  PitBull4LeaderIcon, vv4.0.9
  PitBull4LuaTexts, vv4.0.9
  PitBull4MasterLooterIcon, vv4.0.9
  PitBull4PhaseIcon, vv4.0.9
  PitBull4Portrait, vv4.0.9
  PitBull4PowerBar, vv4.0.9
  PitBull4PvPIcon, vv4.0.9
  PitBull4QuestIcon, vv4.0.9
  PitBull4RaidTargetIcon, vv4.0.9
  PitBull4RangeFader, vv4.0.9
  PitBull4ReadyCheckIcon, vv4.0.9
  PitBull4ReputationBar, vv4.0.9
  PitBull4RestIcon, vv4.0.9
  PitBull4RoleIcon, vv4.0.9
  PitBull4Sounds, vv4.0.9
  PitBull4ThreatBar, vv4.0.9
  PitBull4Totems, vv4.0.9
  PitBull4VisualHeal, vv4.0.9
  PitBull4VoiceIcon, vv4.0.9
  Postal, vv3.5.8
  Prat30, v3.6.15      
  Prat30Libraries, v
  Quartz, v3.3.1
  Recount, vv7.0.3k release
  RelicInspector, v1.11
  SexyMap, vv7.0.0
  SharedMedia, v3.0.7-188
  Stubby, v7.1.5675 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  TipTac, v16.08.30
  TipTacItemRef, v16.08.30
  TipTacTalents, v16.07.21
  WorldFlightMap, vr5
  WoWDBProfiler, v
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=e81)

**Comment by Thunder-Child** [comment]
Date: 2016-10-14 15:48:23
ID: 1
Error occured in: Global
Count: 14
Message: ..\AddOns\Backpack\core\Slots.lua line 93:
   attempt to index local 'Slot' (a nil value)
Debug:
   Backpack\core\Slots.lua:93: UpdateSlot()
   Backpack\core\Slots.lua:189: UpdateContainerSlots()
   Backpack\core\Slots.lua:206: UpdateAllSlots()
   Backpack\core\Core.lua:229: Toggle()
   Backpack\core\Blizzard.lua:8: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
bagID = -3
slotID = 18
event = "OnShow"
itemID = 124120
cached = "Leyblood"
_ = "[Leyblood]"
_ = 1
itemLevel = 101
category = <table> {
 name = "Reagent Bank"
 sortFunc = <function> defined @Interface\AddOns\Backpack\core\Categories.lua:8
 index = 1002
 filterFunc = <function> defined @Interface\AddOns\Backpack\categories\ReagentBank.lua:6
}
categoryIndex = 1002
Slot = nil
(*temporary) = -3
(*temporary) = 18
(*temporary) = nil
(*temporary) = 15
(*temporary) = 1
(*temporary) = -1
(*temporary) = 15
(*temporary) = <table> {
 name = "Reagent Bank"
 sortFunc = <function> defined @Interface\AddOns\Backpack\core\Categories.lua:8
 index = 1002
 filterFunc = <function> defined @Interface\AddOns\Backpack\categories\ReagentBank.lua:6
}
(*temporary) = true
(*temporary) = -3
(*temporary) = "attempt to index local 'Slot' (a nil value)"
P = <table> {
 AddContainerSlot = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:31
 UpdateContainerCooldowns = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:177
 print = <function> defined @Interface\AddOns\Backpack\core\Private.lua:7
 GetContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:52
 UpdateContainerSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:187
 RemoveCategorySlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:234
 Expose = <function> defined @Interface\AddOns\Backpack\core\Core.lua:208
 GetSlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:64
 ResizeContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:56
 CreateSlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:24
 RemoveContainerSlot = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:36
 CreateContainerButton = <function> defined @Interface\AddOns\Backpack\core\ContainerButtons.lua:39
 name = "Backpack"
 noop = <function> defined @Interface\AddOns\Backpack\core\Core.lua:302
 Fire = <function> defined @Interface\AddOns\Backpack\core\Core.lua:181
 categorySlots = <table> {
 }
 UpdateSlotCooldown = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:170
 categories = <table> {
 }
 PositionContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:103
 CreateContainer = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:4
 GetCategory = <function> defined @Interface\AddOns\Backpack\core\Categories.lua:24
 query = <table> {
 }
 InitializeBank = <function> defined @Interface\AddOns\Backpack\core\Core.lua:170
 SkinCallback = <function> defined @Interface\AddOns\Backpack\core\Core.lua:198
 PositionSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:247
 AddCategorySlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:217
 InitializeAllSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:211
 UpdateAllSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:193
 printf = <function> defined @Interface\AddOns\Backpack\core\Private.lua:11
 GetAllContainers = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:48
 UpdateSlotInfo = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:139
 GetCategoryContainer = <function> defined @Interface\AddOns\Backpack\core\Containers.lua:27
 UpdateSlot = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:80
 HasParent = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:76
 GetAllParents = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:72
 GetAllSlots = <function> defined @Interface\AddOns\Backpack\core\Slots.lua:68
 modules = <table> {
 }
 Override = <function> defined @Interface\AddOns\Backpack\core\Core.lua:191
 error = <function> defined @Interface\AddOns\Backpack\core\Private.lua:16
 MixinAPI = <function> defined @Interface\AddOns\Backpack\core\ContainerAPI.lua:121
}

AddOns:
  KalielsTracker, v2.0.6
  Swatter, v7.1.5675 (TasmanianThylacine)
  WowheadLooter, v60014
  Ace3, v
  AceGUI30SharedMediaWidgets, v
  AckisRecipeList, v7.0.3.8
  AckisRecipeListQuickScan, v7.0.3.3
  ACP, v3.4.29 
  AdvancedInterfaceOptions, v1.0.5
  Altoholic, vr171
  AngryWorldQuests, v
  Archy, v7.0.3.17
  Babylonian, v5.1.DEV.332(/embedded)
  Backpack, v70000.3-Beta
  BackpackClassic, v70000.3-Beta
  Bartender4, v4.7.2
  BigWigs, vv18
  BrokerCurrency, v7.0.3.2
  BrokerDurabilityInfo, v1.24
  BrokerEverything, v2.17-Release
  BrokerGarrison, v2.0.8.1
  BrokerMoneyFu, v70000-1
  BrokerProfessionsMenu, v7.0.3.15
  BrokeruClock, vv3.3.9
  ChocolateBar, vv3.0.2
  Configator, v5.1.DEV.406(/embedded)
  CooldownCount, v7.0.1
  CrapAway, v
  Crosshairs, v0.3
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr54
  DBMCore, v
  DBMDefaultSkin, v
  DBMLDB, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DejaCharacterStats, v7.0.3 r16
  ElkBuffBars, v2.5.0-188
  Fizzle, v70000-1
  GatherMate2, v1.37.1
  IceHUD, v1.10.9
  Informant, v7.1.5675 (TasmanianThylacine)
  KuiNameplates, v
  KuiNameplatesCore, v
  KuiNameplatesCoreConfig, v
  LibExtraTip, v5.12.DEV.412(/embedded)
  LibSharedMedia30, v3.0-95
  lsToasts, v1.12
  Mapster, v1.7.2
  Masque, v7.0.1
  MasqueApathy, v7.0.0
  MasqueCaith, v7.0.0
  MasqueEntropy, v7.0.0
  MasqueLiteStep, v7.0.0
  MasqueOnyx, v7.0.0
  MasqueRenaitre, vv7.0.3
  MasqueSerenity, v7.0.0
  MikScrollingBattleText, v5.7.146
  MoveAnything, v16.1.0
  NomiCakes, v7.0.3.13
  OmniCC, v7.0.1
  Pawn, v2.1
  PerfectRaid, vv70000-1.0.0
  PetTracker, v7.0.2
  PetTrackerBreeds, v
  PetTrackerConfig, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  PitBull4, vv4.0.9
  PitBull4Aggro, vv4.0.9
  PitBull4AltManaBar, vv4.0.9
  PitBull4AltPowerBar, vv4.0.9
  PitBull4ArtifactPowerBar, vv4.0.9
  PitBull4Aura, vv4.0.9
  PitBull4Background, vv4.0.9
  PitBull4BattlePet, vv4.0.9
  PitBull4BlankSpace, vv4.0.9
  PitBull4Border, vv4.0.9
  PitBull4CastBar, vv4.0.9
  PitBull4CastBarLatency, vv4.0.9
  PitBull4CombatFader, vv4.0.9
  PitBull4CombatIcon, vv4.0.9
  PitBull4CombatText, vv4.0.9
  PitBull4ComboPoints, vv4.0.9
  PitBull4ExperienceBar, vv4.0.9
  PitBull4HealthBar, vv4.0.9
  PitBull4HideBlizzard, vv4.0.9
  PitBull4Highlight, vv4.0.9
  PitBull4HostilityFader, vv4.0.9
  PitBull4LeaderIcon, vv4.0.9
  PitBull4LuaTexts, vv4.0.9
  PitBull4MasterLooterIcon, vv4.0.9
  PitBull4PhaseIcon, vv4.0.9
  PitBull4Portrait, vv4.0.9
  PitBull4PowerBar, vv4.0.9
  PitBull4PvPIcon, vv4.0.9
  PitBull4QuestIcon, vv4.0.9
  PitBull4RaidTargetIcon, vv4.0.9
  PitBull4RangeFader, vv4.0.9
  PitBull4ReadyCheckIcon, vv4.0.9
  PitBull4ReputationBar, vv4.0.9
  PitBull4RestIcon, vv4.0.9
  PitBull4RoleIcon, vv4.0.9
  PitBull4Sounds, vv4.0.9
  PitBull4ThreatBar, vv4.0.9
  PitBull4Totems, vv4.0.9
  PitBull4VisualHeal, vv4.0.9
  PitBull4VoiceIcon, vv4.0.9
  Postal, vv3.5.8
  Prat30, v3.6.15      
  Prat30Libraries, v
  Quartz, v3.3.1
  Recount, vv7.0.3k release
  RelicInspector, v1.11
  SexyMap, vv7.0.0
  SharedMedia, v3.0.7-188
  Stubby, v7.1.5675 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  TipTac, v16.08.30
  TipTacItemRef, v16.08.30
  TipTacTalents, v16.07.21
  WorldFlightMap, vr5
  WoWDBProfiler, v
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=e6f)

**Comment by p3lim** [comment]
Also related:

https://github.com/p3lim-wow/Backpack/commit/50af43cca84a768a306112c69ef236f2adb227d0
https://github.com/p3lim-wow/Backpack/commit/74caef477a4fb0e1feb555e3c9a1a3a25e35157b
https://github.com/p3lim-wow/Backpack/commit/15d2967cda7947d3b03d301de0bc74e3ea175007
